apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pvc
  labels:
    app: mosquitto
  annotations:
    ves.io/vsites: "appworld2025-k8s-vsite"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
