apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
  annotations:
    ves.io/vsites: "appworld2025-k8s-vsite"
spec:
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 9001
      targetPort: 9001
      name: wss
  selector:
    app: mosquitto
  type: ClusterIP