services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=grafana
     - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
     - NAMESPACE=${NAMESPACE}
    ports:
     - '3000:3000'
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data: